ERROR 2025-06-24 14:58:23,509 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 14:58:23,511 basehttp "GET /services/user_profile/ HTTP/1.1" 500 202
ERROR 2025-06-24 14:58:41,162 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 14:58:41,166 basehttp "GET /services/user_profile/ HTTP/1.1" 500 347
ERROR 2025-06-24 14:59:43,754 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 14:59:43,755 basehttp "GET /services/user_profile/ HTTP/1.1" 500 61
ERROR 2025-06-24 15:01:37,259 log Internal Server Error: /services/user_profile/
Traceback (most recent call last):
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserSerializer is not JSON serializable
ERROR 2025-06-24 15:01:37,274 basehttp "GET /services/user_profile/ HTTP/1.1" 500 127604
ERROR 2025-06-24 15:03:40,590 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 15:03:40,592 basehttp "GET /services/user_profile/ HTTP/1.1" 500 153
ERROR 2025-06-24 15:12:41,492 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 15:12:41,493 basehttp "GET /services/user_profile/ HTTP/1.1" 500 60
ERROR 2025-06-24 15:15:34,292 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 15:15:34,294 basehttp "POST /services/user_profile/ HTTP/1.1" 500 336
ERROR 2025-06-24 15:34:35,163 log Internal Server Error: /services/admin_dashboard/
Traceback (most recent call last):
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\My Work\urban_salon\Backend\urban_salon\company_services\services_views\adminView.py", line 34, in get
    pending_request_data, pending_request_count = assinged_request
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable function object
ERROR 2025-06-24 15:34:35,170 basehttp "GET /services/admin_dashboard/ HTTP/1.1" 500 109187
ERROR 2025-06-24 15:36:43,123 log Internal Server Error: /services/admin_dashboard/
Traceback (most recent call last):
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\My Work\urban_salon\Backend\urban_salon\company_services\services_views\adminView.py", line 49, in get
    pending_request_data, pending_request_count = assigned_request(user)
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\My Work\urban_salon\Backend\urban_salon\company_services\services_views\adminView.py", line 26, in assigned_request
    service_obj = ServiceRequest.objects.filter(delete_flag=False, status='pending', assigned_to=user)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'assigned_to' into field. Choices are: assigned_provider, assigned_provider_id, client, client_id, created_by, created_date, delete_flag, id, is_active, location, payment, ratingreview, scheduled_datetime, service, service_id, status, updated_by, updated_date
ERROR 2025-06-24 15:36:43,138 basehttp "GET /services/admin_dashboard/ HTTP/1.1" 500 161750
ERROR 2025-06-24 19:01:44,930 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 19:01:44,932 basehttp "GET /services/user_profile/ HTTP/1.1" 500 93
ERROR 2025-06-24 19:01:53,075 log Internal Server Error: /services/user_profile/
ERROR 2025-06-24 19:01:53,076 basehttp "GET /services/user_profile/ HTTP/1.1" 500 93
ERROR 2025-06-24 19:16:39,298 log Internal Server Error: /base/signup/
Traceback (most recent call last):
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "d:\My Work\urban_salon\Backend\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\My Work\urban_salon\Backend\urban_salon\base\base_views\SignUpView.py", line 51, in post
    print(path)
          ^^^^
UnboundLocalError: cannot access local variable 'path' where it is not associated with a value
ERROR 2025-06-24 19:16:39,304 basehttp "POST /base/signup/ HTTP/1.1" 500 100039
